trigger:
- manual

pool:
  vmImage: 'macos-latest'

steps:

- task: NodeTool@0
  inputs:
    versionSource: 'spec'
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      npm install -g junit-report-merger
      npm install cypress --save-dev
  displayName: 'npm install'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      npm run bug
  displayName: 'run cypress bug tests'
  continueOnError: true


- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      npm run merge:bugreport
  displayName: 'merge reports'
  continueOnError: true

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: 'qa-bug-test-report.xml'
    searchFolder: '$(System.DefaultWorkingDirectory)'
    failTaskOnFailedTests: false