trigger:
- manual

pr:
  branches:
    include:
      - '*'

pool:
  vmImage: 'macos-latest'

steps:

- task: NodeTool@0
  inputs:
    versionSource: 'spec'
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      npm install -g junit-report-merger
      npm install cypress --save-dev
  displayName: 'npm install'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      npm run integration
  displayName: 'run cypress integration tests'
  continueOnError: true


- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      npm run merge:integrationreport
  displayName: 'merge reports'
  continueOnError: true

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: 'qa-integration-test-report.xml'
    searchFolder: '$(System.DefaultWorkingDirectory)'
    failTaskOnFailedTests: false