name: Cypress Tests
on:
  push:
    branches:
    - main
    paths:
    - tests/cypress-web/**
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    defaults:
      run: 
        shell: bash
        working-directory: tests/cypress-web
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Cypress run
        run:  npm run finapp_tests
      - name: Merge reports
        run: npm run merge:reports
      - name: Sleep
        run: sleep 5
      - name: Upload JUnit test results
        uses: actions/upload-artifact@v2
        with:
          name: junit-results
          path: ./tests/cypress-web/automation-report.xml
      - name: Publish Test Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Cypress Tests
          path: ./tests/cypress-web/automation-report.xml
          reporter: jest-junit

    